workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install XcodeGen
        script: brew install xcodegen
      - name: Generate Xcode project
        script: xcodegen generate
      - name: Build iOS app
        script: |
          xcodebuild -project MarketAlphaElite.xcodeproj \
            -scheme MarketAlphaElite \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/MarketAlphaElite.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/MarketAlphaElite.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist exportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
    publishing:
      email:
        recipients:
          - vighnesh.chauhan11@gmail.com
